### PR TITLE
Compatibility fix for WB1.38

### PR DESCRIPTION
**Pull request by QuentinJanuel**
I implemented the compatibility fix for WB1.38 as described in #20

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Static analysis error:

> Error: Method ProfessionalWiki\AutomatedValues\Compat::newPId() should return Wikibase\DataModel\Entity\PropertyId but returns Wikibase\DataModel\Entity\NumericPropertyId.

**Comment by JeroenDeDauw** [comment]
Can likely be fixed by running Psalm and PHPStan with MW 38, so they know that NumericProperyId implements ProperyId.

You can modify that in https://github.com/ProfessionalWiki/AutomatedValues/blob/master/.github/workflows/ci.yml. There you can also make the unit tests run with MW 38.

**Comment by QuentinJanuel** [comment]
Thanks for the suggestion, sadly it still doesn't work because AutomatedValues still doesn't seem fully compatible with WB38. For instance here is the error for PHPStan:
error

**Comment by QuentinJanuel** [comment]
Hey, I think I solved the PHPStan and Psalm issues, but meanwhile I cleared the github workflow caches and now `PHPUnit: MW REL1_35, PHP 7.4` fails at `Run composer update` with
```
Error: Failed to clone https://github.com/wikimedia/avro-php.git via https, ssh protocols, aborting.
```

Indeed, this repo seems to no longer exist. Do you have any suggestion of what I should do?

**Comment by JeroenDeDauw** [comment]
Don't forget to update https://github.com/ProfessionalWiki/AutomatedValues/blob/master/.github/workflows/ci.yml#L14-L19. Could perhaps include MW 39 right away

**Comment by JeroenDeDauw** [comment]
You can include the Compat.php file from analysis via https://github.com/ProfessionalWiki/AutomatedValues/blob/master/phpstan.neon#L10-L12 and https://github.com/ProfessionalWiki/AutomatedValues/blob/master/psalm.xml#L12-L15

There are also other Psalm failures about Wikibase classes not being found, dunno what is causing those. [WikibaseExport](https://github.com/ProfessionalWiki/WikibaseExport) runs checks with 38 without problems. Then again, you could switch Psalm and PHPStan back to older MW versions if they pass on those with `Compat.php` being excluded.

**Comment by QuentinJanuel** [comment]
Okay this should be working fine now, I have included MW38 in PHPUnit (sadly MW39 doesn't seem to work but I didn't investigate)

The workflows are running fine on my side
image

If they don't for you, that's probably because of cache issues: I think your Psalm and PHPStan are running using MW37 despite the CI indicating MW38 because it is already cached. I cleared the cache and everything works fine for me.

**Comment by JeroenDeDauw** [comment]
Thank you @QuentinJanuel! We applied your changes via https://github.com/ProfessionalWiki/AutomatedValues/pull/28

**Pull request closed without merging**
